export const DEFAULT_THEME_ID = "ocean-blue";
export const THEME_STORAGE_KEY = "pulse.theme.active";
export const CUSTOM_THEMES_STORAGE_KEY = "pulse.theme.custom";
export const WALLPAPER_STORAGE_KEY = "pulse.wallpaper.active";
export const WALLPAPER_IMAGE_STORAGE_KEY = "pulse.wallpaper.image";

export const THEME_VARIABLES = [
  "--color-primary",
  "--color-primary-fg",
  "--color-secondary",
  "--color-bg",
  "--color-card",
  "--color-border",
  "--color-fg",
  "--color-muted",
  "--color-muted-fg",
  "--color-bubble-me",
  "--color-bubble-them",
  "--color-success",
  "--color-danger",
  "--color-warning",
];

export const predefinedThemes = [
  {
    id: "ocean-blue",
    name: "Ocean Blue",
    description: "Default premium blue glass theme.",
    variables: {
      "--color-primary": "#3B82F6",
      "--color-primary-fg": "#FFFFFF",
      "--color-secondary": "#60A5FA",
      "--color-bg": "#0B1120",
      "--color-card": "#111827",
      "--color-border": "#1F2937",
      "--color-fg": "#F9FAFB",
      "--color-muted": "#182235",
      "--color-muted-fg": "#94A3B8",
      "--color-bubble-me": "#1D4ED8",
      "--color-bubble-them": "#172033",
      "--color-success": "#22C55E",
      "--color-danger": "#EF4444",
      "--color-warning": "#F59E0B",
    },
  },
  {
    id: "emerald-green",
    name: "Emerald Green",
    description: "Calm green with deep glass surfaces.",
    variables: {
      "--color-primary": "#10B981",
      "--color-primary-fg": "#FFFFFF",
      "--color-secondary": "#34D399",
      "--color-bg": "#06130F",
      "--color-card": "#0E1F1A",
      "--color-border": "#1F3A32",
      "--color-fg": "#F0FDF9",
      "--color-muted": "#142A23",
      "--color-muted-fg": "#9BB7AD",
      "--color-bubble-me": "#047857",
      "--color-bubble-them": "#14251F",
      "--color-success": "#22C55E",
      "--color-danger": "#F43F5E",
      "--color-warning": "#FBBF24",
    },
  },
  {
    id: "purple-night",
    name: "Purple Night",
    description: "Elegant violet for late-night focus.",
    variables: {
      "--color-primary": "#8B5CF6",
      "--color-primary-fg": "#FFFFFF",
      "--color-secondary": "#A78BFA",
      "--color-bg": "#100B1F",
      "--color-card": "#19142B",
      "--color-border": "#31264A",
      "--color-fg": "#FAF5FF",
      "--color-muted": "#241B3A",
      "--color-muted-fg": "#AFA4C4",
      "--color-bubble-me": "#6D28D9",
      "--color-bubble-them": "#251D3A",
      "--color-success": "#22C55E",
      "--color-danger": "#EF4444",
      "--color-warning": "#F59E0B",
    },
  },
  {
    id: "crimson-red",
    name: "Crimson Red",
    description: "Sharp, confident, and editorial.",
    variables: {
      "--color-primary": "#EF4444",
      "--color-primary-fg": "#FFFFFF",
      "--color-secondary": "#FB7185",
      "--color-bg": "#170A0D",
      "--color-card": "#241114",
      "--color-border": "#3F2025",
      "--color-fg": "#FFF7F7",
      "--color-muted": "#30191D",
      "--color-muted-fg": "#C4A0A4",
      "--color-bubble-me": "#B91C1C",
      "--color-bubble-them": "#2D171B",
      "--color-success": "#22C55E",
      "--color-danger": "#F43F5E",
      "--color-warning": "#FBBF24",
    },
  },
  {
    id: "orange-sunset",
    name: "Orange Sunset",
    description: "Warm glass with soft depth.",
    variables: {
      "--color-primary": "#F97316",
      "--color-primary-fg": "#FFFFFF",
      "--color-secondary": "#FDBA74",
      "--color-bg": "#17100A",
      "--color-card": "#241A12",
      "--color-border": "#3E2D20",
      "--color-fg": "#FFF7ED",
      "--color-muted": "#302317",
      "--color-muted-fg": "#C6AA8F",
      "--color-bubble-me": "#C2410C",
      "--color-bubble-them": "#2D2117",
      "--color-success": "#22C55E",
      "--color-danger": "#EF4444",
      "--color-warning": "#F59E0B",
    },
  },
  {
    id: "cyber-neon",
    name: "Cyber Neon",
    description: "Electric, high-contrast realtime energy.",
    variables: {
      "--color-primary": "#22D3EE",
      "--color-primary-fg": "#050A12",
      "--color-secondary": "#A3E635",
      "--color-bg": "#050A12",
      "--color-card": "#0A1220",
      "--color-border": "#163047",
      "--color-fg": "#ECFEFF",
      "--color-muted": "#101D2C",
      "--color-muted-fg": "#8FB4C0",
      "--color-bubble-me": "#0891B2",
      "--color-bubble-them": "#101B2B",
      "--color-success": "#A3E635",
      "--color-danger": "#FB7185",
      "--color-warning": "#FDE047",
    },
  },
  {
    id: "midnight-black",
    name: "Midnight Black",
    description: "Minimal black with crisp contrast.",
    variables: {
      "--color-primary": "#E5E7EB",
      "--color-primary-fg": "#030712",
      "--color-secondary": "#9CA3AF",
      "--color-bg": "#030712",
      "--color-card": "#0B0F19",
      "--color-border": "#1F2937",
      "--color-fg": "#F9FAFB",
      "--color-muted": "#111827",
      "--color-muted-fg": "#9CA3AF",
      "--color-bubble-me": "#374151",
      "--color-bubble-them": "#111827",
      "--color-success": "#22C55E",
      "--color-danger": "#EF4444",
      "--color-warning": "#F59E0B",
    },
  },
  {
    id: "rose-pink",
    name: "Rose Pink",
    description: "Soft premium rose for expressive chats.",
    variables: {
      "--color-primary": "#EC4899",
      "--color-primary-fg": "#FFFFFF",
      "--color-secondary": "#F9A8D4",
      "--color-bg": "#180A13",
      "--color-card": "#25111D",
      "--color-border": "#432239",
      "--color-fg": "#FFF7FB",
      "--color-muted": "#321928",
      "--color-muted-fg": "#C6A0B6",
      "--color-bubble-me": "#BE185D",
      "--color-bubble-them": "#2E1726",
      "--color-success": "#22C55E",
      "--color-danger": "#EF4444",
      "--color-warning": "#F59E0B",
    },
  },
  {
    id: "indigo-glass",
    name: "Indigo Glass",
    description: "SaaS polish with cool indigo depth.",
    variables: {
      "--color-primary": "#6366F1",
      "--color-primary-fg": "#FFFFFF",
      "--color-secondary": "#818CF8",
      "--color-bg": "#0B1024",
      "--color-card": "#111831",
      "--color-border": "#273152",
      "--color-fg": "#F8FAFC",
      "--color-muted": "#19213D",
      "--color-muted-fg": "#A4AED0",
      "--color-bubble-me": "#4338CA",
      "--color-bubble-them": "#18213B",
      "--color-success": "#22C55E",
      "--color-danger": "#EF4444",
      "--color-warning": "#F59E0B",
    },
  },
  {
    id: "arctic-white",
    name: "Arctic White",
    description: "Bright, clean, and spacious.",
    light: true,
    variables: {
      "--color-primary": "#2563EB",
      "--color-primary-fg": "#FFFFFF",
      "--color-secondary": "#60A5FA",
      "--color-bg": "#EEF4FF",
      "--color-card": "#FFFFFF",
      "--color-border": "#D9E2F2",
      "--color-fg": "#0F172A",
      "--color-muted": "#E7EEF9",
      "--color-muted-fg": "#64748B",
      "--color-bubble-me": "#DBEAFE",
      "--color-bubble-them": "#FFFFFF",
      "--color-success": "#16A34A",
      "--color-danger": "#DC2626",
      "--color-warning": "#D97706",
    },
  },
];

export const wallpaperOptions = [
  { id: "none", name: "None", description: "A clean, flat message canvas." },
  { id: "gradient", name: "Gradient", description: "Soft luminous depth." },
  { id: "dots", name: "Dots", description: "Subtle texture for scanning." },
  { id: "lines", name: "Lines", description: "Quiet geometric rhythm." },
  { id: "mesh", name: "Mesh", description: "Premium layered glow." },
  { id: "dark-blur", name: "Dark Blur", description: "Smoky glass atmosphere." },
  { id: "blue-blur", name: "Blue Blur", description: "Cool focused ambience." },
  { id: "purple-blur", name: "Purple Blur", description: "Night studio glow." },
  { id: "green-blur", name: "Green Blur", description: "Calm organic glow." },
  { id: "custom", name: "Custom Image", description: "Use your own image URL." },
];

export function buildCustomTheme({
  id,
  name,
  primary,
  background,
  card,
  myBubble,
  otherBubble,
  text,
}) {
  return {
    id,
    name,
    description: "Custom Pulse theme",
    custom: true,
    variables: {
      "--color-primary": primary,
      "--color-primary-fg": text,
      "--color-secondary": primary,
      "--color-bg": background,
      "--color-card": card,
      "--color-border": primary,
      "--color-fg": text,
      "--color-muted": otherBubble,
      "--color-muted-fg": text,
      "--color-bubble-me": myBubble,
      "--color-bubble-them": otherBubble,
      "--color-success": primary,
      "--color-danger": "#EF4444",
      "--color-warning": "#F59E0B",
    },
  };
}
